// Public websites verified on 2026-09-30. Build durations require the owner's input.
export const projects = [
  {
    name: 'AIM Faucet',
    embeddable: true,
    buildType: 'Custom WordPress website',
    stack: 'WordPress · WooCommerce · BeTheme',
    type: 'B2B manufacturing & retail',
    year: null,
    duration: null,
    goal: 'Build a clear B2B-first website for trade buyers, while supporting retail orders.',
    roleNote: 'Custom WordPress website developed by me. Handed over for SEO and ongoing work.',
    liveUrl: 'https://www.aimfaucet.com/',
    image: '/projects/aim-faucet-desktop.webp',
    mobileImage: '/projects/aim-faucet-mobile.webp',
  },
  {
    name: 'Astrodai',
    buildType: 'Custom-coded website',
    stack: 'Astro · TypeScript · JavaScript · CSS · Three.js',
    embeddable: true,
    type: 'Digital product & commerce',
    year: '2026',
    duration: null,
    goal: 'Build a responsive product website that connects clear reading options, pricing, and a guided purchase flow.',
    liveUrl: 'https://astrodai.in/',
    image: '/projects/astrodai-desktop.webp',
    mobileImage: '/projects/astrodai-mobile.webp',
  },
  {
    name: 'Canada Immigration Advisory',
    buildType: 'Custom-coded website',
    stack: 'Next.js · React · TypeScript · Tailwind CSS · Motion · Three.js',
    type: 'Professional services',
    year: '2026',
    duration: null,
    goal: 'Develop a responsive services website with an interactive eligibility calculator and clear enquiry paths.',
    liveUrl: 'https://canada-immigration-advisory.vercel.app/',
    image: '/projects/canada-advisory-desktop.webp',
    mobileImage: '/projects/canada-advisory-mobile.webp',
  },
  {
    name: 'Synthesis Capital', type: 'Investment & food technology',
    goal: 'Present the investment focus, portfolio companies, and team in a clear, responsive experience.',
    buildType: 'Custom-coded website',
    stack: 'Next.js · React',
    liveUrl: 'https://www.synthesis.capital/', embeddable: true,
    image: '/projects/synthesis-desktop.webp', mobileImage: '/projects/synthesis-mobile.webp',
  },
  {
    name: 'CosyToys', type: 'B2B manufacturing & wholesale',
    goal: 'Help wholesale buyers explore plush toys and find a clear route to a manufacturing enquiry.',
    buildType: 'Custom-coded website',
    stack: 'HTML · CSS · JavaScript',
    liveUrl: 'https://cosytoys.in/', embeddable: true,
    image: '/projects/cosytoys-desktop.webp', mobileImage: '/projects/cosytoys-mobile.webp',
  },
  {
    name: 'Dream Miles Consultants',
    type: 'Travel & visa consultancy',
    goal: 'Build a clear travel website that presents destinations, trip planning, and visa services with a direct route to enquiries.',
    roleNote: 'Custom WordPress website development.',
    buildType: 'Custom WordPress website',
    stack: 'WordPress · Elementor · WP Travel Engine · WooCommerce',
    liveUrl: 'https://dreammilesconsultants.com/',
    embeddable: true,
    image: '/projects/dream-miles-desktop.webp',
    mobileImage: '/projects/dream-miles-mobile.webp',
  },
];
