// Throwaway UI prototype: three folder structures, selected via ?variant=A|B|C.
const projects=[
{name:'Forma',type:'BRAND & DIGITAL EXPERIENCE',year:'2026',color:'#c0c99e',title:'A little space.<br>A better everyday.',desc:'A considered digital home for objects that make everyday life a little more beautiful.',site:'Objects for<br>slower living.',tags:['Art direction','Web design'],url:'forma.example'},
{name:'Offscript',type:'EDITORIAL PLATFORM',year:'2025',color:'#b1a1c9',title:'Stories outside<br>the ordinary.',desc:'An independent journal for unexpected perspectives, with an expressive reading experience.',site:'Stay curious.<br>Go offscript.',tags:['Identity','Development'],url:'offscript.example'},
{name:'Sunday Club',type:'COMMUNITY & COMMERCE',year:'2025',color:'#e9aa74',title:'For the love<br>of going nowhere.',desc:'A warm, welcoming space for a community that believes in taking the scenic route.',site:'Less rush.<br>More Sunday.',tags:['Strategy','E-commerce'],url:'sunday.example'},
{name:'Common Ground',type:'CULTURE & IDENTITY',year:'2025',color:'#dcdb81',title:'Different people.<br>Shared ground.',desc:'A flexible identity and website for a space built around conversation and connection.',site:'Meet in<br>the middle.',tags:['Branding','Web design'],url:'common.example'},
{name:'Still Studio',type:'PORTFOLIO & DIRECTION',year:'2024',color:'#8fb9b4',title:'Room to pause.<br>Space to see.',desc:'A quiet digital portfolio where photography takes the lead and the interface steps back.',site:'The art<br>of noticing.',tags:['Photography','Development'],url:'still.example'},
{name:'Field Notes',type:'EXPERIMENTAL JOURNAL',year:'2024',color:'#cc9486',title:'Small observations.<br>New possibilities.',desc:'An ongoing collection of visual experiments, creative coding, and things noticed along the way.',site:'Look a<br>little closer.',tags:['Creative coding','Exploration'],url:'fieldnotes.example'},
{name:'Parallel',type:'PRODUCT DESIGN',year:'2023',color:'#aaaeca',title:'Make room<br>for better work.',desc:'A focused workspace concept for small teams with big ideas.',site:'In sync.<br>In your flow.',tags:['Product design','Prototype'],url:'parallel.example'},
{name:'After Hours',type:'PLAY & EXPLORATION',year:'2023',color:'#b9b6a9',title:'Nothing serious.<br>Something good.',desc:'A playground of small experiments made simply for the joy of making.',site:'Made<br>after hours.',tags:['Experiments','Motion'],url:'afterhours.example'}];
const variants={A:['The stacked archive','01 / THE STACKED ARCHIVE'],B:['The reading room','02 / THE READING ROOM'],C:['The open desktop','03 / THE OPEN DESKTOP']};
let variant=new URLSearchParams(location.search).get('variant')||'A';if(!variants[variant])variant='A';let active=variant==='B'?0:-1;
const archive=document.querySelector('#archive');
function detail(p){return `<div class="project-detail"><div class="project-copy"><p class="eyebrow">${p.year} / SAMPLE PROJECT</p><h2>${p.title}</h2><p>${p.desc}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div></div><div class="preview" aria-label="Illustrative website preview"><div class="browser-bar"><i></i><i></i><i></i><span>${p.url} · illustrative preview</span></div><div class="site"><div class="site-nav">${p.name.toLowerCase()}<span>STORY &nbsp; COLLECTION &nbsp; ↗</span></div><h3>${p.site}</h3><p>Thoughtfully made. Carefully considered.<br>Something worth spending time with.</p><span class="mini-cta">Explore the collection ↗</span><div class="orb"></div></div></div></div>`}
function folder(p,i){return `<article class="folder ${active===i?'open':''}" style="--color:${p.color}"><button class="folder-trigger" aria-expanded="${active===i}" aria-controls="body-${i}" data-index="${i}"><span class="tab">${p.name}<small>${String(i+1).padStart(2,'0')}</small></span><span class="folder-band"><span>${p.type}</span><span>${active===i?'−':'↗'}</span></span></button><div class="folder-body" id="body-${i}"><div class="body-inner">${detail(p)}</div></div></article>`}
function render(){document.body.dataset.variant=variant;document.querySelector('#variant-label').textContent=`${variant} — ${variants[variant][0]}`;document.querySelector('#direction').textContent=variants[variant][1];archive.innerHTML=variant==='B'?`<div class="folder-list">${projects.map(folder).join('')}</div><aside class="persistent-preview">${detail(projects[active<0?0:active])}</aside>`:projects.map(folder).join('');if(variant==='B'&&innerWidth>680)archive.querySelectorAll('.folder-body').forEach(el=>el.style.display='none');}
archive.addEventListener('click',e=>{const trigger=e.target.closest('[data-index]');if(!trigger)return;const index=Number(trigger.dataset.index);active=active===index?-1:index;if(variant==='B'||variant==='C'){render();return;}archive.querySelectorAll('.folder').forEach((el,i)=>{el.classList.toggle('open',i===active);el.querySelector('button').setAttribute('aria-expanded',i===active);el.querySelector('.folder-band span:last-child').textContent=i===active?'−':'↗';});});
function cycle(delta){const keys=Object.keys(variants);variant=keys[(keys.indexOf(variant)+delta+3)%3];active=variant==='B'?0:-1;const url=new URL(location);url.searchParams.set('variant',variant);history.replaceState({},'',url);render();}
document.querySelector('#prev').onclick=()=>cycle(-1);document.querySelector('#next').onclick=()=>cycle(1);document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,[contenteditable]'))return;if(e.key==='ArrowLeft')cycle(-1);if(e.key==='ArrowRight')cycle(1);});document.querySelector('.about').onclick=()=>document.querySelector('dialog').showModal();document.querySelector('.close-about').onclick=()=>document.querySelector('dialog').close();let mobile=innerWidth<=680;addEventListener('resize',()=>{if(mobile!==(innerWidth<=680)){mobile=innerWidth<=680;render();}});render();
