// Throwaway UI prototype: three folder structures, selected via ?variant=A|B|C.
const projects=[
{name:'Forma',type:'BRAND & DIGITAL EXPERIENCE',year:'2026',color:'#c0c99e',title:'A little space.<br>A better everyday.',desc:'A considered digital home for objects that make everyday life a little more beautiful.',site:'Objects for<br>slower living.',tags:['Art direction','Web design'],url:'forma.example'},
{name:'Offscript',type:'EDITORIAL PLATFORM',year:'2025',color:'#b1a1c9',title:'Stories outside<br>the ordinary.',desc:'An independent journal for unexpected perspectives, with an expressive reading experience.',site:'Stay curious.<br>Go offscript.',tags:['Identity','Development'],url:'offscript.example'},
{name:'Sunday Club',type:'COMMUNITY & COMMERCE',year:'2025',color:'#e9aa74',title:'For the love<br>of going nowhere.',desc:'A warm, welcoming space for a community that believes in taking the scenic route.',site:'Less rush.<br>More Sunday.',tags:['Strategy','E-commerce'],url:'sunday.example'},
{name:'Common Ground',type:'CULTURE & IDENTITY',year:'2025',color:'#dcdb81',title:'Different people.<br>Shared ground.',desc:'A flexible identity and website for a space built around conversation and connection.',site:'Meet in<br>the middle.',tags:['Branding','Web design'],url:'common.example'},
{name:'Still Studio',type:'PORTFOLIO & DIRECTION',year:'2024',color:'#8fb9b4',title:'Room to pause.<br>Space to see.',desc:'A quiet digital portfolio where photography takes the lead and the interface steps back.',site:'The art<br>of noticing.',tags:['Photography','Development'],url:'still.example'},
{name:'Field Notes',type:'EXPERIMENTAL JOURNAL',year:'2024',color:'#cc9486',title:'Small observations.<br>New possibilities.',desc:'An ongoing collection of visual experiments, creative coding, and things noticed along the way.',site:'Look a<br>little closer.',tags:['Creative coding','Exploration'],url:'fieldnotes.example'},
{name:'Parallel',type:'PRODUCT DESIGN',year:'2023',color:'#aaaeca',title:'Make room<br>for better work.',desc:'A focused workspace concept for small teams with big ideas.',site:'In sync.<br>In your flow.',tags:['Product design','Prototype'],url:'parallel.example'},
{name:'After Hours',type:'PLAY & EXPLORATION',year:'2023',color:'#b9b6a9',title:'Nothing serious.<br>Something good.',desc:'A playground of small experiments made simply for the joy of making.',site:'Made<br>after hours.',tags:['Experiments','Motion'],url:'afterhours.example'}];
projects.push(
{name:'The person',type:'ABOUT / THE HUMAN SIDE',year:'01',color:'#dad2b9',kind:'about',title:'Curious by default.<br>Always making.',desc:'Your story belongs here: what draws you to design, what you care about, and the things you bring to every project.',tags:['Your story','Your approach']},
{name:'The journey',type:'EXPERIENCE / ALONG THE WAY',year:'02',color:'#aebbb0',kind:'journey',title:'Every chapter<br>leaves a mark.',desc:'A compact timeline of your work, collaborations, and milestones. These entries are placeholders for your real experience.',tags:['Experience','Learning']},
{name:'Say hello',type:'CONTACT / THE NEXT CHAPTER',year:'03',color:'#d7b49d',kind:'contact',title:'Something in mind?<br>Let’s start there.',desc:'Your email and social links will live right here. No separate contact page, no form to get lost in.',tags:['Contact','Collaboration']}
);
const variants={A:['The spring stack','01 / SPRING STACK'],B:['The floating window','02 / FLOATING WINDOW'],C:['The horizontal archive','03 / HORIZONTAL ARCHIVE']};
let variant=new URLSearchParams(location.search).get('variant')||'C';if(!variants[variant])variant='A';let active=-1;
const archive=document.querySelector('#archive');
let revealTimer;
function detail(p){if(p.kind)return personal(p);return `<div class="project-detail"><div class="project-copy"><p class="eyebrow">${p.year} / SAMPLE PROJECT</p><h2>${p.title}</h2><p>${p.desc}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div></div><div class="preview" aria-label="Illustrative website preview"><div class="browser-bar"><i></i><i></i><i></i><span>${p.url} · illustrative preview</span></div><div class="site"><div class="site-nav">${p.name.toLowerCase()}<span>STORY &nbsp; COLLECTION &nbsp; ↗</span></div><h3>${p.site}</h3><p>Thoughtfully made. Carefully considered.<br>Something worth spending time with.</p><span class="mini-cta">Explore the collection ↗</span><div class="orb"></div></div></div></div>`}
function personal(p){const content=p.kind==='about'?'<div class="personal-art"><span>hello.</span><small>A PLACE FOR YOUR PORTRAIT & A LITTLE PERSONALITY</small></div>':p.kind==='journey'?'<div class="timeline"><div><small>NOW</small><h3>Your current chapter</h3><p>Role, studio, or independent practice</p></div><div><small>BEFORE</small><h3>Where you grew</h3><p>A previous role or meaningful collaboration</p></div><div><small>THE BEGINNING</small><h3>What started it all</h3><p>Your first step into making things</p></div></div>':'<div class="contact-note"><span>To the next<br><em>good idea.</em></span><p>Email & social links go here once you share them.</p><small>THIS IS THE START OF A CONVERSATION ↗</small></div>';return `<div class="project-detail personal"><div class="project-copy"><p class="eyebrow">${p.type}</p><h2>${p.title}</h2><p>${p.desc}</p></div>${content}</div>`;}
function folder(p,i){return `<article class="folder ${active===i?'open':''}" style="--color:${p.color}"><button class="folder-trigger" aria-expanded="${active===i}" aria-controls="body-${i}" data-index="${i}"><span class="tab">${p.name}<small>${String(i+1).padStart(2,'0')}</small></span><span class="folder-band"><span>${p.type}</span><span>${active===i?'−':'↗'}</span></span></button><div class="folder-body" id="body-${i}"><div class="body-inner">${detail(p)}</div></div></article>`}
function render(){document.body.dataset.variant='A';document.body.dataset.motion=variant;document.querySelector('#variant-label').textContent=`${variant} — ${variants[variant][0]}`;document.querySelector('#direction').textContent=variants[variant][1];archive.innerHTML=projects.map(folder).join('');}
archive.addEventListener('click',e=>{const trigger=e.target.closest('[data-index]');if(!trigger)return;const index=Number(trigger.dataset.index);active=active===index?-1:index;archive.querySelectorAll('.folder').forEach((el,i)=>{el.classList.toggle('open',i===active);el.querySelector('button').setAttribute('aria-expanded',i===active);el.querySelector('.folder-band span:last-child').textContent=i===active?'−':'↗';});document.body.classList.toggle('has-open',active>=0);if(variant==='C'&&active>=0){const selected=trigger.closest('.folder');clearTimeout(revealTimer);revealTimer=setTimeout(()=>{if(selected.classList.contains('open'))revealFolder(selected);},matchMedia('(prefers-reduced-motion: reduce)').matches?0:780);}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){active=-1;document.body.classList.remove('has-open');render();}});

function cycle(delta){document.body.classList.remove('has-open');const keys=Object.keys(variants);variant=keys[(keys.indexOf(variant)+delta+3)%3];active=-1;const url=new URL(location);url.searchParams.set('variant',variant);history.replaceState({},'',url);render();}
document.querySelector('#prev').onclick=()=>cycle(-1);document.querySelector('#next').onclick=()=>cycle(1);document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,[contenteditable]'))return;if(e.key==='ArrowLeft')cycle(-1);if(e.key==='ArrowRight')cycle(1);});document.querySelector('.about').onclick=()=>{const button=document.querySelector('[data-index="8"]');if(active!==8)button.click();button.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});};document.querySelector('.close-about').onclick=()=>document.querySelector('dialog').close();let mobile=innerWidth<=680;addEventListener('resize',()=>{if(mobile!==(innerWidth<=680)){mobile=innerWidth<=680;render();}});render();

function revealFolder(folder){archive.scrollTo({left:archive.scrollLeft+folder.getBoundingClientRect().left-archive.getBoundingClientRect().left-10,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}
for(const [id,step] of [['rail-prev',-1],['rail-next',1]])document.getElementById(id).onclick=()=>archive.scrollBy({left:step*archive.clientWidth*.7,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});
