// Throwaway UI prototype: three folder structures, selected via ?variant=A|B|C.
const projects=[
{name:'Forma',type:'BRAND & DIGITAL EXPERIENCE',year:'2026',color:'#c0c99e',title:'A little space.<br>A better everyday.',desc:'A considered digital home for objects that make everyday life a little more beautiful.',site:'Objects for<br>slower living.',tags:['Art direction','Web design'],url:'forma.example'},
{name:'Offscript',type:'EDITORIAL PLATFORM',year:'2025',color:'#b1a1c9',title:'Stories outside<br>the ordinary.',desc:'An independent journal for unexpected perspectives, with an expressive reading experience.',site:'Stay curious.<br>Go offscript.',tags:['Identity','Development'],url:'offscript.example'},
{name:'Sunday Club',type:'COMMUNITY & COMMERCE',year:'2025',color:'#e9aa74',title:'For the love<br>of going nowhere.',desc:'A warm, welcoming space for a community that believes in taking the scenic route.',site:'Less rush.<br>More Sunday.',tags:['Strategy','E-commerce'],url:'sunday.example'},
{name:'Common Ground',type:'CULTURE & IDENTITY',year:'2025',color:'#dcdb81',title:'Different people.<br>Shared ground.',desc:'A flexible identity and website for a space built around conversation and connection.',site:'Meet in<br>the middle.',tags:['Branding','Web design'],url:'common.example'},
{name:'Still Studio',type:'PORTFOLIO & DIRECTION',year:'2024',color:'#8fb9b4',title:'Room to pause.<br>Space to see.',desc:'A quiet digital portfolio where photography takes the lead and the interface steps back.',site:'The art<br>of noticing.',tags:['Photography','Development'],url:'still.example'},
{name:'Field Notes',type:'EXPERIMENTAL JOURNAL',year:'2024',color:'#cc9486',title:'Small observations.<br>New possibilities.',desc:'An ongoing collection of visual experiments, creative coding, and things noticed along the way.',site:'Look a<br>little closer.',tags:['Creative coding','Exploration'],url:'fieldnotes.example'},
{name:'Parallel',type:'PRODUCT DESIGN',year:'2023',color:'#aaaeca',title:'Make room<br>for better work.',desc:'A focused workspace concept for small teams with big ideas.',site:'In sync.<br>In your flow.',tags:['Product design','Prototype'],url:'parallel.example'},
{name:'After Hours',type:'PLAY & EXPLORATION',year:'2023',color:'#b9b6a9',title:'Nothing serious.<br>Something good.',desc:'A playground of small experiments made simply for the joy of making.',site:'Made<br>after hours.',tags:['Experiments','Motion'],url:'afterhours.example'}];
projects.push(
{name:'The person',type:'ABOUT / THE HUMAN SIDE',year:'01',color:'#dad2b9',kind:'about',title:'Curious by default.<br>Always making.',desc:'Your story belongs here: what draws you to design, what you care about, and the things you bring to every project.',tags:['Your story','Your approach']},
{name:'The journey',type:'EXPERIENCE / ALONG THE WAY',year:'02',color:'#aebbb0',kind:'journey',title:'Every chapter<br>leaves a mark.',desc:'A compact timeline of your work, collaborations, and milestones. These entries are placeholders for your real experience.',tags:['Experience','Learning']},
{name:'Say hello',type:'CONTACT / THE NEXT CHAPTER',year:'03',color:'#d7b49d',kind:'contact',title:'Something in mind?<br>Let’s start there.',desc:'Your email and social links will live right here. No separate contact page, no form to get lost in.',tags:['Contact','Collaboration']}
);
const durations=['4 weeks','3 weeks','6 weeks','4 weeks','2 weeks','Ongoing','5 weeks','Weekend'];
const goals=['Make considered objects effortless to discover and buy.','Give independent stories a distinctive home and a better reading experience.','Turn a shared interest into a welcoming, shoppable community.','Help people discover a cultural space and feel part of it.','Let the photography lead, with a quiet and intuitive portfolio.','Create a home for observations, experiments, and creative play.','Make everyday teamwork feel focused and effortless.','Explore what a small idea can become without a brief.'];
const view=document.querySelector('#projects');
view.innerHTML=projects.slice(0,8).map((p,i)=>`<article class="project-stage theme-${i%4}" style="--accent:${p.color};--layer:${i+1}" aria-labelledby="project-${i}"><div class="project-info"><div class="index-line"><span>PROJECT / ${String(i+1).padStart(2,'0')}</span><span>${p.year}</span></div><h1 id="project-${i}">${p.name}</h1><p class="project-kind">${p.type}</p><dl><div><dt>TIME TAKEN</dt><dd>${durations[i]} <small>sample</small></dd></div><div><dt>THE GOAL</dt><dd>${goals[i]}</dd></div></dl><div class="project-bottom"><span class="sample-status"><i></i> CONCEPT PREVIEW</span><button class="detail-toggle" aria-expanded="false" aria-controls="note-${i}">Project notes <span>＋</span></button></div><p class="project-note" id="note-${i}" hidden>${p.desc} This is sample content for the design study.</p></div><div class="poster-stack"><div class="stack-sheet sheet-back" aria-hidden="true"></div><div class="stack-sheet sheet-front" aria-hidden="true"></div><div class="project-poster"><div class="poster-top"><span>${p.tags[0]}</span><span>${durations[i]}</span></div><div class="poster-title">${p.site}</div><div class="poster-art" aria-hidden="true"><div class="sculpture"></div><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><span class="art-word">${p.name.toUpperCase()}</span></div><div class="mini-window"><div class="window-head"><span>● ● ●</span><span>${p.url}</span><span>↗</span></div><div class="window-content"><span class="window-brand">${p.name.toLowerCase()}</span><strong>${p.site}</strong><span class="window-line"></span><span class="window-line short"></span><span class="window-button">EXPLORE THE COLLECTION</span><div class="window-object"></div></div></div><div class="poster-foot"><span>${p.name.toUpperCase()}®</span><span>DESIGN / DEVELOPMENT</span></div></div><div class="under-poster"><span>ILLUSTRATIVE WEBSITE PREVIEW</span><span>${String(i+1).padStart(2,'0')} — 08</span></div></div></article>`).join('');
document.querySelectorAll('.detail-toggle').forEach(button=>button.onclick=()=>{const note=document.getElementById(button.getAttribute('aria-controls'));note.hidden=!note.hidden;button.setAttribute('aria-expanded',!note.hidden);button.querySelector('span').textContent=note.hidden?'＋':'−';});
let workScroll=0;document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{if(button.classList.contains('active'))return;const work=button.dataset.tab==='work';if(!work)workScroll=scrollY;document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',b===button);});document.querySelector('#work-panel').hidden=!work;document.querySelector('#personal-panel').hidden=work;window.scrollTo({top:work?workScroll:0,behavior:'instant'});});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>entry.target.classList.toggle('in-view',entry.isIntersecting)),{threshold:.2});document.querySelectorAll('.project-stage').forEach(stage=>observer.observe(stage));
function clock(){document.querySelector('#clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',hour12:false})+' / LOCAL TIME';}clock();setInterval(clock,60000);
const contact=document.querySelector('#contact-dialog');document.querySelector('#contact-button').onclick=()=>contact.showModal();document.querySelectorAll('[data-contact]').forEach(b=>b.onclick=()=>contact.showModal());document.querySelector('#close-contact').onclick=()=>contact.close();document.querySelector('#back-work').onclick=()=>contact.close();
