// Throwaway UI prototype: three folder structures, selected via ?variant=A|B|C.
const projects=[
{name:'Forma',type:'BRAND & DIGITAL EXPERIENCE',year:'2026',color:'#c0c99e',title:'A little space.<br>A better everyday.',desc:'A considered digital home for objects that make everyday life a little more beautiful.',site:'Objects for<br>slower living.',tags:['Art direction','Web design'],url:'forma.example'},
{name:'Offscript',type:'EDITORIAL PLATFORM',year:'2025',color:'#b1a1c9',title:'Stories outside<br>the ordinary.',desc:'An independent journal for unexpected perspectives, with an expressive reading experience.',site:'Stay curious.<br>Go offscript.',tags:['Identity','Development'],url:'offscript.example'},
{name:'Sunday Club',type:'COMMUNITY & COMMERCE',year:'2025',color:'#e9aa74',title:'For the love<br>of going nowhere.',desc:'A warm, welcoming space for a community that believes in taking the scenic route.',site:'Less rush.<br>More Sunday.',tags:['Strategy','E-commerce'],url:'sunday.example'},
{name:'Common Ground',type:'CULTURE & IDENTITY',year:'2025',color:'#dcdb81',title:'Different people.<br>Shared ground.',desc:'A flexible identity and website for a space built around conversation and connection.',site:'Meet in<br>the middle.',tags:['Branding','Web design'],url:'common.example'},
{name:'Still Studio',type:'PORTFOLIO & DIRECTION',year:'2024',color:'#8fb9b4',title:'Room to pause.<br>Space to see.',desc:'A quiet digital portfolio where photography takes the lead and the interface steps back.',site:'The art<br>of noticing.',tags:['Photography','Development'],url:'still.example'},
{name:'Field Notes',type:'EXPERIMENTAL JOURNAL',year:'2024',color:'#cc9486',title:'Small observations.<br>New possibilities.',desc:'An ongoing collection of visual experiments, creative coding, and things noticed along the way.',site:'Look a<br>little closer.',tags:['Creative coding','Exploration'],url:'fieldnotes.example'},
{name:'Parallel',type:'PRODUCT DESIGN',year:'2023',color:'#aaaeca',title:'Make room<br>for better work.',desc:'A focused workspace concept for small teams with big ideas.',site:'In sync.<br>In your flow.',tags:['Product design','Prototype'],url:'parallel.example'},
{name:'After Hours',type:'PLAY & EXPLORATION',year:'2023',color:'#b9b6a9',title:'Nothing serious.<br>Something good.',desc:'A playground of small experiments made simply for the joy of making.',site:'Made<br>after hours.',tags:['Experiments','Motion'],url:'afterhours.example'}];
projects.push(
{name:'The person',type:'ABOUT / THE HUMAN SIDE',year:'01',color:'#dad2b9',kind:'about',title:'Curious by default.<br>Always making.',desc:'Your story belongs here: what draws you to design, what you care about, and the things you bring to every project.',tags:['Your story','Your approach']},
{name:'The journey',type:'EXPERIENCE / ALONG THE WAY',year:'02',color:'#aebbb0',kind:'journey',title:'Every chapter<br>leaves a mark.',desc:'A compact timeline of your work, collaborations, and milestones. These entries are placeholders for your real experience.',tags:['Experience','Learning']},
{name:'Say hello',type:'CONTACT / THE NEXT CHAPTER',year:'03',color:'#d7b49d',kind:'contact',title:'Something in mind?<br>Let’s start there.',desc:'Your email and social links will live right here. No separate contact page, no form to get lost in.',tags:['Contact','Collaboration']}
);
function detail(p){if(p.kind)return personal(p);return `<div class="project-detail"><div class="project-copy"><p class="eyebrow">${p.year} / SAMPLE PROJECT</p><h2>${p.title}</h2><p>${p.desc}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div></div><div class="preview" aria-label="Illustrative website preview"><div class="browser-bar"><i></i><i></i><i></i><span>${p.url} · illustrative preview</span></div><div class="site"><div class="site-nav">${p.name.toLowerCase()}<span>STORY &nbsp; COLLECTION &nbsp; ↗</span></div><h3>${p.site}</h3><p>Thoughtfully made. Carefully considered.<br>Something worth spending time with.</p><span class="mini-cta">Explore the collection ↗</span><div class="orb"></div></div></div></div>`}
function personal(p){const content=p.kind==='about'?'<div class="personal-art"><span>hello.</span><small>A PLACE FOR YOUR PORTRAIT & A LITTLE PERSONALITY</small></div>':p.kind==='journey'?'<div class="timeline"><div><small>NOW</small><h3>Your current chapter</h3><p>Role, studio, or independent practice</p></div><div><small>BEFORE</small><h3>Where you grew</h3><p>A previous role or meaningful collaboration</p></div><div><small>THE BEGINNING</small><h3>What started it all</h3><p>Your first step into making things</p></div></div>':'<div class="contact-note"><span>To the next<br><em>good idea.</em></span><p>Email & social links go here once you share them.</p><small>THIS IS THE START OF A CONVERSATION ↗</small></div>';return `<div class="project-detail personal"><div class="project-copy"><p class="eyebrow">${p.type}</p><h2>${p.title}</h2><p>${p.desc}</p></div>${content}</div>`;}
const archive=document.querySelector('#archive');
let active=-1;
let revealTimer;
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
function render(){archive.innerHTML=projects.map((p,i)=>`<article class="folder" style="--color:${p.color};--order:${i%3}" data-folder="${i}"><button class="folder-trigger" id="trigger-${i}" aria-expanded="false" aria-controls="content-${i}" data-index="${i}"><span class="tab"><span>${p.name}</span><small>${String(i+1).padStart(2,'0')}</small></span><span class="cover"><span class="cover-art art-${i%4}"><span class="art-ring"></span><span class="art-shape"></span><span class="art-type">${p.kind?'A little<br>more human.':p.site}</span><span class="art-caption">${p.kind?'BEHIND THE WORK':'SELECTED DIGITAL EXPERIENCE'}</span></span><span class="cover-foot"><span>${p.kind?'PERSONAL FILE':p.tags[0]} <span class="year">/ ${p.year}</span></span><span class="open-icon">↗</span></span></span></button><div class="folder-body" id="content-${i}" role="region" aria-labelledby="trigger-${i}" inert><div class="body-inner"><div class="inside-top"><span>${p.kind?'A LITTLE MORE ABOUT ME':p.type}</span><button class="close" data-close="${i}" aria-label="Close ${p.name}">Close <span>×</span></button></div>${detail(p)}</div></div></article>`).join('');}
function select(index){active=active===index?-1:index;clearTimeout(revealTimer);archive.querySelectorAll('.folder').forEach((el,i)=>{const open=i===active;el.classList.toggle('open',open);el.querySelector('.folder-trigger').setAttribute('aria-expanded',String(open));el.querySelector('.folder-body').inert=!open;});document.body.classList.toggle('has-open',active>=0);document.querySelector('#selection').textContent=active<0?'Made to be explored.':`${String(active+1).padStart(2,'0')} / ${projects[active].name} — ${projects[active].kind?'personal file':'sample project'}`;if(active>=0){const el=archive.children[active];revealTimer=setTimeout(()=>{archive.scrollTo({left:archive.scrollLeft+el.getBoundingClientRect().left-archive.getBoundingClientRect().left-24,behavior:reduced()?'instant':'smooth'});},reduced()?0:720);}}
archive.addEventListener('click',e=>{const close=e.target.closest('[data-close]');if(close){const i=Number(close.dataset.close);select(i);document.querySelector(`#trigger-${i}`).focus({preventScroll:true});return;}const trigger=e.target.closest('[data-index]');if(trigger)select(Number(trigger.dataset.index));});
archive.addEventListener('keydown',e=>{const trigger=e.target.closest('[data-index]');if(e.key==='Escape'&&active>=0){const i=active;select(i);document.querySelector(`#trigger-${i}`).focus({preventScroll:true});}if(trigger&&['ArrowRight','ArrowLeft'].includes(e.key)){e.preventDefault();const i=Number(trigger.dataset.index);archive.querySelector(`[data-index="${Math.max(0,Math.min(projects.length-1,i+(e.key==='ArrowRight'?1:-1)))}"]`).focus();}});
for(const [id,step] of [['rail-prev',-1],['rail-next',1]])document.getElementById(id).onclick=()=>archive.scrollBy({left:step*archive.clientWidth*.75,behavior:reduced()?'instant':'smooth'});
function openPersonal(index){if(active!==index)select(index);archive.scrollIntoView({behavior:reduced()?'instant':'smooth',block:'nearest'});document.querySelector(`#trigger-${index}`).focus({preventScroll:true});}
document.querySelector('#about').onclick=()=>openPersonal(8);document.querySelector('#contact').onclick=()=>openPersonal(10);document.querySelector('#work').onclick=()=>{if(active>=0)select(active);archive.scrollTo({left:0,behavior:reduced()?'instant':'smooth'});};
render();
