// Throwaway UI prototype: three folder structures, selected via ?variant=A|B|C.
const projects=[
{name:'Forma',type:'BRAND & DIGITAL EXPERIENCE',year:'2026',color:'#c0c99e',title:'A little space.<br>A better everyday.',desc:'A considered digital home for objects that make everyday life a little more beautiful.',site:'Objects for<br>slower living.',tags:['Art direction','Web design'],url:'forma.example'},
{name:'Offscript',type:'EDITORIAL PLATFORM',year:'2025',color:'#b1a1c9',title:'Stories outside<br>the ordinary.',desc:'An independent journal for unexpected perspectives, with an expressive reading experience.',site:'Stay curious.<br>Go offscript.',tags:['Identity','Development'],url:'offscript.example'},
{name:'Sunday Club',type:'COMMUNITY & COMMERCE',year:'2025',color:'#e9aa74',title:'For the love<br>of going nowhere.',desc:'A warm, welcoming space for a community that believes in taking the scenic route.',site:'Less rush.<br>More Sunday.',tags:['Strategy','E-commerce'],url:'sunday.example'},
{name:'Common Ground',type:'CULTURE & IDENTITY',year:'2025',color:'#dcdb81',title:'Different people.<br>Shared ground.',desc:'A flexible identity and website for a space built around conversation and connection.',site:'Meet in<br>the middle.',tags:['Branding','Web design'],url:'common.example'},
{name:'Still Studio',type:'PORTFOLIO & DIRECTION',year:'2024',color:'#8fb9b4',title:'Room to pause.<br>Space to see.',desc:'A quiet digital portfolio where photography takes the lead and the interface steps back.',site:'The art<br>of noticing.',tags:['Photography','Development'],url:'still.example'},
{name:'Field Notes',type:'EXPERIMENTAL JOURNAL',year:'2024',color:'#cc9486',title:'Small observations.<br>New possibilities.',desc:'An ongoing collection of visual experiments, creative coding, and things noticed along the way.',site:'Look a<br>little closer.',tags:['Creative coding','Exploration'],url:'fieldnotes.example'},
{name:'Parallel',type:'PRODUCT DESIGN',year:'2023',color:'#aaaeca',title:'Make room<br>for better work.',desc:'A focused workspace concept for small teams with big ideas.',site:'In sync.<br>In your flow.',tags:['Product design','Prototype'],url:'parallel.example'},
{name:'After Hours',type:'PLAY & EXPLORATION',year:'2023',color:'#b9b6a9',title:'Nothing serious.<br>Something good.',desc:'A playground of small experiments made simply for the joy of making.',site:'Made<br>after hours.',tags:['Experiments','Motion'],url:'afterhours.example'}];
projects.push(
{name:'The person',type:'ABOUT / THE HUMAN SIDE',year:'01',color:'#dad2b9',kind:'about',title:'Curious by default.<br>Always making.',desc:'Your story belongs here: what draws you to design, what you care about, and the things you bring to every project.',tags:['Your story','Your approach']},
{name:'The journey',type:'EXPERIENCE / ALONG THE WAY',year:'02',color:'#aebbb0',kind:'journey',title:'Every chapter<br>leaves a mark.',desc:'A compact timeline of your work, collaborations, and milestones. These entries are placeholders for your real experience.',tags:['Experience','Learning']},
{name:'Say hello',type:'CONTACT / THE NEXT CHAPTER',year:'03',color:'#d7b49d',kind:'contact',title:'Something in mind?<br>Let’s start there.',desc:'Your email and social links will live right here. No separate contact page, no form to get lost in.',tags:['Contact','Collaboration']}
);
function detail(p){if(p.kind)return personal(p);return `<div class="project-detail"><div class="project-copy"><p class="eyebrow">${p.year} / SAMPLE PROJECT</p><h2>${p.title}</h2><p>${p.desc}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div></div><div class="preview" aria-label="Illustrative website preview"><div class="browser-bar"><i></i><i></i><i></i><span>${p.url} · illustrative preview</span></div><div class="site"><div class="site-nav">${p.name.toLowerCase()}<span>STORY &nbsp; COLLECTION &nbsp; ↗</span></div><h3>${p.site}</h3><p>Thoughtfully made. Carefully considered.<br>Something worth spending time with.</p><span class="mini-cta">Explore the collection ↗</span><div class="orb"></div></div></div></div>`}
function personal(p){const content=p.kind==='about'?'<div class="personal-art"><span>hello.</span><small>A PLACE FOR YOUR PORTRAIT & A LITTLE PERSONALITY</small></div>':p.kind==='journey'?'<div class="timeline"><div><small>NOW</small><h3>Your current chapter</h3><p>Role, studio, or independent practice</p></div><div><small>BEFORE</small><h3>Where you grew</h3><p>A previous role or meaningful collaboration</p></div><div><small>THE BEGINNING</small><h3>What started it all</h3><p>Your first step into making things</p></div></div>':'<div class="contact-note"><span>To the next<br><em>good idea.</em></span><p>Email & social links go here once you share them.</p><small>THIS IS THE START OF A CONVERSATION ↗</small></div>';return `<div class="project-detail personal"><div class="project-copy"><p class="eyebrow">${p.type}</p><h2>${p.title}</h2><p>${p.desc}</p></div>${content}</div>`;}
const tiles=document.querySelector('#tiles');
const cardMarkup=(p,i)=>`<button class="tile project-tile cabinet-file" style="--accent:${p.color};--i:${i}" data-project="${i}" aria-label="Open ${p.name} project folder"><span class="folder-shell" aria-hidden="true"><span class="folder-paper"></span><span class="folder-front"><img src="covers/project-${i}.svg" alt="" draggable="false"></span></span></button>`;
const aboutCard=`<button class="tile about-tile" data-project="8"><span class="tile-top"><span>09 / THE PERSON</span><span class="tile-arrow">↗</span></span><span class="dot-face" aria-hidden="true"><span>· ·</span><span>⌣</span></span><span class="tile-bottom"><span><strong>A human, after all.</strong><small>A little more about the maker</small></span><span class="tiny-dot"></span></span></button>`;
const contactCard=`<button class="tile contact-tile" data-contact><span class="tile-top"><span>10 / THE NEXT GOOD THING</span><span class="tile-arrow">↗</span></span><span class="contact-tile-title">Your idea.<br>Our next<br><em>great thing.</em></span><span class="tile-bottom"><span>Start a conversation</span><span class="glass orange">↗</span></span></button>`;
let filter='all';
function renderTiles(){tiles.innerHTML=(filter!=='personal'?projects.slice(0,8).map(cardMarkup).join(''):'')+(filter!=='work'?aboutCard+contactCard:'');}
renderTiles();
document.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>{filter=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',b===button);});renderTiles();});
const projectDialog=document.querySelector('#project-dialog');
function openProject(i){const p=projects[i];document.querySelector('#dialog-label').textContent=`${String(i+1).padStart(2,'0')} / ${p.name.toUpperCase()} · ${p.kind?'PERSONAL FILE':'SAMPLE PROJECT'}`;document.querySelector('#project-content').innerHTML=detail(p);projectDialog.style.setProperty('--accent',p.color);projectDialog.showModal();}
tiles.addEventListener('click',e=>{const button=e.target.closest('[data-project]');if(button&& !document.body.classList.contains('dimensional-tabs'))openProject(Number(button.dataset.project));});
document.querySelectorAll('.dialog-close').forEach(button=>button.onclick=()=>button.closest('dialog').close());document.querySelectorAll('dialog:not(#tab-detail)').forEach(dialog=>dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}}));
const menu=document.querySelector('#contact-menu'),contactToggle=document.querySelector('#contact-toggle');function toggleContact(force){const open=force??menu.hidden;menu.hidden=!open;contactToggle.setAttribute('aria-expanded',open);contactToggle.setAttribute('aria-label',open?'Close contact menu':'Open contact menu');contactToggle.querySelector('.glass').textContent=open?'×':'↗';}
contactToggle.onclick=()=>toggleContact();document.addEventListener('click',e=>{if(e.target.closest('[data-contact]'))toggleContact(true);});
function showContact(){toggleContact(false);document.querySelector('#contact-dialog').showModal();}
document.querySelector('#draft-open').onclick=showContact;document.querySelector('#note-open').onclick=showContact;document.querySelector('#about-open').onclick=()=>{toggleContact(false);openProject(8);};
document.querySelector('#contact-form').onsubmit=e=>{e.preventDefault();const text=`From: ${document.querySelector('#sender-email').value}\n\n${document.querySelector('#message').value}\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='project-message-draft.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);document.querySelector('#draft-status').textContent='Draft saved to your device. Nothing has been sent.';};
let islandMode='today';const islandToggle=document.querySelector('#island-toggle'),panel=document.querySelector('#island-panel');islandToggle.onclick=()=>{panel.hidden=!panel.hidden;islandToggle.setAttribute('aria-expanded',!panel.hidden);islandToggle.querySelector('.island-plus').textContent=panel.hidden?'+':'−';renderIsland();};
function renderIsland(){const now=new Date();document.querySelector('#island-time').textContent=now.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',hour12:false});document.querySelector('#island-date').textContent=now.toLocaleDateString('en',{month:'short',day:'numeric'});const content=document.querySelector('#island-content');content.setAttribute('aria-labelledby',`tab-${islandMode}`);if(islandMode==='today'){const monday=new Date(now);monday.setDate(now.getDate()-((now.getDay()+6)%7));content.innerHTML=`<div class="widget-heading"><strong>${now.toLocaleDateString('en',{month:'long',year:'numeric'})}</strong><small>YOUR LOCAL TIME</small></div><div class="week">${Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(monday.getDate()+i);return `<div><small>${d.toLocaleDateString('en',{weekday:'short'}).slice(0,2)}</small><span class="${d.toDateString()===now.toDateString()?'today':''}">${d.getDate()}</span></div>`;}).join('')}</div>`;}else if(islandMode==='weather'){content.innerHTML='<div class="widget-heading"><strong>Weather preview</strong><small>SAMPLE · NOT LIVE</small></div><div class="weather"><span class="weather-icon">☀</span><strong>23°</strong><div>Mostly sunny<small>Choose a city to connect weather</small></div></div><div class="forecast"><span>NOW<br>☀ 23°</span><span>16:00<br>☀ 24°</span><span>17:00<br>☁ 22°</span><span>18:00<br>☁ 21°</span></div>';}else{const percent=Math.floor((now.getHours()*60+now.getMinutes())/1440*100);content.innerHTML=`<div class="widget-heading"><strong>Your day</strong><strong>${percent}%</strong></div><div class="day-dots">${Array.from({length:32},(_,i)=>`<i class="${i/32*100<percent?'lit':''}"></i>`).join('')}</div><p class="widget-note">A little room left to make something good.</p>`;}}
document.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>{islandMode=button.dataset.mode;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-selected',b===button));renderIsland();});
document.querySelector('.island-tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const buttons=[...document.querySelectorAll('[data-mode]')];const i=buttons.indexOf(document.activeElement);const next=buttons[(i+(e.key==='ArrowRight'?1:2))%3];next.focus();next.click();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){toggleContact(false);if(!panel.hidden){panel.hidden=true;islandToggle.setAttribute('aria-expanded',false);islandToggle.querySelector('.island-plus').textContent='+';islandToggle.focus();}}});renderIsland();setInterval(renderIsland,60000);
